manifest:
  remotes:
    - name: AngryPancake
      url-base: https://github.com/AngryPancake
  projects:
    # Together with the above defined remote, this refers to a module located at
    # https://github.com/remote-name/repository-name
    - name: zmk-behavior-tda
      remote: AngryPancake
      # This points to a west manifest file in the remote module for further imports
      import: west.yml